# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'page_5.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QHBoxLayout, QPushButton,
    QSizePolicy, QTextEdit, QVBoxLayout, QWidget)

class Ui_page_5(object):
    def setupUi(self, page_5):
        if not page_5.objectName():
            page_5.setObjectName(u"page_5")
        page_5.resize(712, 484)
        self.verticalLayout = QVBoxLayout(page_5)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.comboBox = QComboBox(page_5)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setMinimumSize(QSize(0, 25))
        self.comboBox.setEditable(True)

        self.horizontalLayout.addWidget(self.comboBox)

        self.pushButton = QPushButton(page_5)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setMinimumSize(QSize(0, 30))
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoDefault(True)

        self.horizontalLayout.addWidget(self.pushButton)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.textEdit = QTextEdit(page_5)
        self.textEdit.setObjectName(u"textEdit")

        self.verticalLayout.addWidget(self.textEdit)


        self.retranslateUi(page_5)

        self.pushButton.setDefault(True)


        QMetaObject.connectSlotsByName(page_5)
    # setupUi

    def retranslateUi(self, page_5):
        page_5.setWindowTitle(QCoreApplication.translate("page_5", u"Form", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("page_5", u"DEV-001", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("page_5", u"DEV-002", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("page_5", u"DEV-003", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("page_5", u"DEV-004", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("page_5", u"DEV-005", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("page_5", u"DEV-006", None))
        self.comboBox.setItemText(6, QCoreApplication.translate("page_5", u"DEV-007", None))
        self.comboBox.setItemText(7, QCoreApplication.translate("page_5", u"DEV-008", None))
        self.comboBox.setItemText(8, QCoreApplication.translate("page_5", u"DEV-009", None))
        self.comboBox.setItemText(9, QCoreApplication.translate("page_5", u"DEV-010", None))
        self.comboBox.setItemText(10, QCoreApplication.translate("page_5", u"DEV-011", None))
        self.comboBox.setItemText(11, QCoreApplication.translate("page_5", u"DEV-012", None))
        self.comboBox.setItemText(12, QCoreApplication.translate("page_5", u"DEV-013", None))
        self.comboBox.setItemText(13, QCoreApplication.translate("page_5", u"DEV-014", None))
        self.comboBox.setItemText(14, QCoreApplication.translate("page_5", u"DEV-015", None))
        self.comboBox.setItemText(15, QCoreApplication.translate("page_5", u"DEV-016", None))
        self.comboBox.setItemText(16, QCoreApplication.translate("page_5", u"DEV-017", None))
        self.comboBox.setItemText(17, QCoreApplication.translate("page_5", u"DEV-018", None))
        self.comboBox.setItemText(18, QCoreApplication.translate("page_5", u"DEV-019", None))
        self.comboBox.setItemText(19, QCoreApplication.translate("page_5", u"DEV-020", None))
        self.comboBox.setItemText(20, QCoreApplication.translate("page_5", u"DEV-021", None))
        self.comboBox.setItemText(21, QCoreApplication.translate("page_5", u"DEV-022", None))
        self.comboBox.setItemText(22, QCoreApplication.translate("page_5", u"DEV-023", None))
        self.comboBox.setItemText(23, QCoreApplication.translate("page_5", u"DEV-024", None))
        self.comboBox.setItemText(24, QCoreApplication.translate("page_5", u"DEV-025", None))
        self.comboBox.setItemText(25, QCoreApplication.translate("page_5", u"DEV-026", None))
        self.comboBox.setItemText(26, QCoreApplication.translate("page_5", u"DEV-027", None))
        self.comboBox.setItemText(27, QCoreApplication.translate("page_5", u"DEV-028", None))
        self.comboBox.setItemText(28, QCoreApplication.translate("page_5", u"DEV-029", None))
        self.comboBox.setItemText(29, QCoreApplication.translate("page_5", u"DEV-030", None))
        self.comboBox.setItemText(30, QCoreApplication.translate("page_5", u"DEV-031", None))
        self.comboBox.setItemText(31, QCoreApplication.translate("page_5", u"DEV-032", None))
        self.comboBox.setItemText(32, QCoreApplication.translate("page_5", u"DEV-033", None))
        self.comboBox.setItemText(33, QCoreApplication.translate("page_5", u"DEV-034", None))
        self.comboBox.setItemText(34, QCoreApplication.translate("page_5", u"DEV-035", None))
        self.comboBox.setItemText(35, QCoreApplication.translate("page_5", u"DEV-036", None))
        self.comboBox.setItemText(36, QCoreApplication.translate("page_5", u"DEV-037", None))
        self.comboBox.setItemText(37, QCoreApplication.translate("page_5", u"DEV-038", None))
        self.comboBox.setItemText(38, QCoreApplication.translate("page_5", u"DEV-039", None))
        self.comboBox.setItemText(39, QCoreApplication.translate("page_5", u"DEV-040", None))
        self.comboBox.setItemText(40, QCoreApplication.translate("page_5", u"DEV-041", None))
        self.comboBox.setItemText(41, QCoreApplication.translate("page_5", u"DEV-042", None))
        self.comboBox.setItemText(42, QCoreApplication.translate("page_5", u"DEV-043", None))
        self.comboBox.setItemText(43, QCoreApplication.translate("page_5", u"DEV-044", None))
        self.comboBox.setItemText(44, QCoreApplication.translate("page_5", u"DEV-045", None))
        self.comboBox.setItemText(45, QCoreApplication.translate("page_5", u"DEV-046", None))
        self.comboBox.setItemText(46, QCoreApplication.translate("page_5", u"DEV-047", None))
        self.comboBox.setItemText(47, QCoreApplication.translate("page_5", u"DEV-048", None))
        self.comboBox.setItemText(48, QCoreApplication.translate("page_5", u"DEV-049", None))
        self.comboBox.setItemText(49, QCoreApplication.translate("page_5", u"DEV-050", None))
        self.comboBox.setItemText(50, QCoreApplication.translate("page_5", u"DEV-051", None))
        self.comboBox.setItemText(51, QCoreApplication.translate("page_5", u"DEV-052", None))
        self.comboBox.setItemText(52, QCoreApplication.translate("page_5", u"DEV-053", None))
        self.comboBox.setItemText(53, QCoreApplication.translate("page_5", u"DEV-054", None))
        self.comboBox.setItemText(54, QCoreApplication.translate("page_5", u"DEV-055", None))
        self.comboBox.setItemText(55, QCoreApplication.translate("page_5", u"DEV-056", None))
        self.comboBox.setItemText(56, QCoreApplication.translate("page_5", u"DEV-057", None))
        self.comboBox.setItemText(57, QCoreApplication.translate("page_5", u"DEV-058", None))
        self.comboBox.setItemText(58, QCoreApplication.translate("page_5", u"DEV-059", None))
        self.comboBox.setItemText(59, QCoreApplication.translate("page_5", u"DEV-060", None))
        self.comboBox.setItemText(60, QCoreApplication.translate("page_5", u"DEV-061", None))
        self.comboBox.setItemText(61, QCoreApplication.translate("page_5", u"DEV-062", None))
        self.comboBox.setItemText(62, QCoreApplication.translate("page_5", u"DEV-063", None))
        self.comboBox.setItemText(63, QCoreApplication.translate("page_5", u"DEV-064", None))
        self.comboBox.setItemText(64, QCoreApplication.translate("page_5", u"DEV-065", None))
        self.comboBox.setItemText(65, QCoreApplication.translate("page_5", u"DEV-066", None))
        self.comboBox.setItemText(66, QCoreApplication.translate("page_5", u"DEV-067", None))
        self.comboBox.setItemText(67, QCoreApplication.translate("page_5", u"DEV-068", None))
        self.comboBox.setItemText(68, QCoreApplication.translate("page_5", u"DEV-069", None))
        self.comboBox.setItemText(69, QCoreApplication.translate("page_5", u"DEV-070", None))
        self.comboBox.setItemText(70, QCoreApplication.translate("page_5", u"DEV-071", None))
        self.comboBox.setItemText(71, QCoreApplication.translate("page_5", u"DEV-072", None))
        self.comboBox.setItemText(72, QCoreApplication.translate("page_5", u"DEV-073", None))
        self.comboBox.setItemText(73, QCoreApplication.translate("page_5", u"DEV-074", None))
        self.comboBox.setItemText(74, QCoreApplication.translate("page_5", u"DEV-075", None))
        self.comboBox.setItemText(75, QCoreApplication.translate("page_5", u"DEV-076", None))
        self.comboBox.setItemText(76, QCoreApplication.translate("page_5", u"DEV-077", None))
        self.comboBox.setItemText(77, QCoreApplication.translate("page_5", u"DEV-078", None))
        self.comboBox.setItemText(78, QCoreApplication.translate("page_5", u"DEV-079", None))
        self.comboBox.setItemText(79, QCoreApplication.translate("page_5", u"DEV-080", None))
        self.comboBox.setItemText(80, QCoreApplication.translate("page_5", u"DEV-081", None))
        self.comboBox.setItemText(81, QCoreApplication.translate("page_5", u"DEV-082", None))
        self.comboBox.setItemText(82, QCoreApplication.translate("page_5", u"DEV-083", None))
        self.comboBox.setItemText(83, QCoreApplication.translate("page_5", u"DEV-084", None))
        self.comboBox.setItemText(84, QCoreApplication.translate("page_5", u"DEV-085", None))
        self.comboBox.setItemText(85, QCoreApplication.translate("page_5", u"DEV-086", None))
        self.comboBox.setItemText(86, QCoreApplication.translate("page_5", u"DEV-087", None))
        self.comboBox.setItemText(87, QCoreApplication.translate("page_5", u"DEV-088", None))
        self.comboBox.setItemText(88, QCoreApplication.translate("page_5", u"DEV-089", None))
        self.comboBox.setItemText(89, QCoreApplication.translate("page_5", u"DEV-090", None))
        self.comboBox.setItemText(90, QCoreApplication.translate("page_5", u"DEV-091", None))
        self.comboBox.setItemText(91, QCoreApplication.translate("page_5", u"DEV-092", None))
        self.comboBox.setItemText(92, QCoreApplication.translate("page_5", u"DEV-093", None))
        self.comboBox.setItemText(93, QCoreApplication.translate("page_5", u"DEV-094", None))
        self.comboBox.setItemText(94, QCoreApplication.translate("page_5", u"DEV-095", None))
        self.comboBox.setItemText(95, QCoreApplication.translate("page_5", u"DEV-096", None))
        self.comboBox.setItemText(96, QCoreApplication.translate("page_5", u"DEV-097", None))
        self.comboBox.setItemText(97, QCoreApplication.translate("page_5", u"DEV-098", None))
        self.comboBox.setItemText(98, QCoreApplication.translate("page_5", u"DEV-099", None))
        self.comboBox.setItemText(99, QCoreApplication.translate("page_5", u"DEV-100", None))

        self.pushButton.setText(QCoreApplication.translate("page_5", u"\u67e5\u8be2\u8bbe\u5907\u6545\u969c\u8bb0\u5f55", None))
    # retranslateUi

